import { sqliteTable, foreignKey, integer, text, uniqueIndex, index } from "drizzle-orm/sqlite-core"

export const activityLogs = sqliteTable("activity_logs", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	action: text().notNull(),
	description: text().notNull(),
	performedBy: text("performed_by"),
	createdAt: integer("created_at", { mode: "timestamp" }).default(
		new Date("2026-04-11T09:55:23.550Z"),
	),
});

export const aiAnalysisLogs = sqliteTable("ai_analysis_logs", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	agentName: text("agent_name").notNull(),
	promptVersionId: text("prompt_version_id"),
	confidenceScore: integer("confidence_score"),
	humanAdjudicationReason: text("human_adjudication_reason"),
	narrative: text(),
	rawOutput: text("raw_output"),
	createdAt: integer("created_at").notNull(),
});

export const aiFeedbackLogs = sqliteTable("ai_feedback_logs", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	aiOutcome: text("ai_outcome").notNull(),
	aiConfidence: integer("ai_confidence"),
	aiCheckType: text("ai_check_type").notNull(),
	humanOutcome: text("human_outcome").notNull(),
	adjudicationReason: text("adjudication_reason").notNull(),
	adjudicationDetail: text("adjudication_detail"),
	adjudicationNotes: text("adjudication_notes"),
	isDivergent: integer("is_divergent").notNull(),
	divergenceWeight: integer("divergence_weight"),
	divergenceType: text("divergence_type"),
	decidedBy: text("decided_by").notNull(),
	decidedAt: integer("decided_at").notNull(),
	relatedFailureEventId: integer("related_failure_event_id").references(() => workflowEvents.id),
	consumedForRetraining: integer("consumed_for_retraining", { mode: "boolean" }).default(
		false,
	),
	consumedAt: integer("consumed_at"),
});

export const applicantMagiclinkForms = sqliteTable("applicant_magiclink_forms", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	workflowId: integer("workflow_id").references(() => workflows.id),
	formType: text("form_type").notNull(),
	status: text().default("pending").notNull(),
	tokenHash: text("token_hash").notNull(),
	token: text(),
	tokenPrefix: text("token_prefix"),
	sentAt: integer("sent_at"),
	viewedAt: integer("viewed_at"),
	expiresAt: integer("expires_at"),
	submittedAt: integer("submitted_at"),
	decisionStatus: text("decision_status"),
	decisionOutcome: text("decision_outcome"),
	decisionReason: text("decision_reason"),
	decisionAt: integer("decision_at"),
	createdAt: integer("created_at").notNull(),
},
(table) => [
	uniqueIndex("applicant_magiclink_forms_token_hash_unique").on(table.tokenHash),
]);

export const applicantSubmissions = sqliteTable("applicant_submissions", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantMagiclinkFormId: integer("applicant_magiclink_form_id").notNull().references(() => applicantMagiclinkForms.id),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	workflowId: integer("workflow_id").references(() => workflows.id),
	formType: text("form_type").notNull(),
	data: text().notNull(),
	submittedBy: text("submitted_by"),
	version: integer().default(1),
	submittedAt: integer("submitted_at").notNull(),
});

export const applicants = sqliteTable("applicants", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	companyName: text("company_name").notNull(),
	tradingName: text("trading_name"),
	registrationNumber: text("registration_number"),
	vatNumber: text("vat_number"),
	contactName: text("contact_name").notNull(),
	idNumber: text("id_number"),
	email: text().notNull(),
	phone: text(),
	businessType: text("business_type"),
	entityType: text("entity_type"),
	productType: text("product_type"),
	industry: text(),
	employeeCount: integer("employee_count"),
	mandateType: text("mandate_type"),
	mandateVolume: integer("mandate_volume"),
	estimatedTransactionsPerMonth: integer("estimated_transactions_per_month"),
	status: text().default("new").notNull(),
	riskLevel: text("risk_level"),
	itcScore: integer("itc_score"),
	itcStatus: text("itc_status"),
	escalationTier: integer("escalation_tier").default(1),
	salvageDeadline: integer("salvage_deadline"),
	isSalvaged: integer("is_salvaged", { mode: "boolean" }).default(false),
	sanctionStatus: text("sanction_status").default("clear"),
	accountExecutive: text("account_executive"),
	notes: text(),
	createdAt: integer("created_at").notNull(),
	updatedAt: integer("updated_at").notNull(),
});

export const documentUploads = sqliteTable("document_uploads", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	internalFormId: integer("internal_form_id").references(() => internalForms.id),
	category: text().notNull(),
	documentType: text("document_type").notNull(),
	fileName: text("file_name").notNull(),
	fileSize: integer("file_size").notNull(),
	fileContent: text("file_content"),
	mimeType: text("mime_type").notNull(),
	storageKey: text("storage_key").notNull(),
	storageUrl: text("storage_url"),
	verificationStatus: text("verification_status").default("pending").notNull(),
	verificationNotes: text("verification_notes"),
	verifiedBy: text("verified_by"),
	verifiedAt: integer("verified_at"),
	expiresAt: integer("expires_at"),
	metadata: text(),
	uploadedBy: text("uploaded_by"),
	uploadedAt: integer("uploaded_at").notNull(),
});

export const documents = sqliteTable("documents", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	type: text().notNull(),
	status: text().default("pending").notNull(),
	category: text(),
	source: text(),
	fileName: text("file_name"),
	fileContent: text("file_content"),
	mimeType: text("mime_type"),
	storageUrl: text("storage_url"),
	uploadedBy: text("uploaded_by"),
	uploadedAt: integer("uploaded_at"),
	verifiedAt: integer("verified_at"),
	processedAt: integer("processed_at"),
	processingStatus: text("processing_status"),
	processingResult: text("processing_result"),
	notes: text(),
});

export const internalForms = sqliteTable("internal_forms", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	formType: text("form_type").notNull(),
	status: text().default("not_started").notNull(),
	currentStep: integer("current_step").default(1).notNull(),
	totalSteps: integer("total_steps").default(1).notNull(),
	lastSavedAt: integer("last_saved_at"),
	submittedAt: integer("submitted_at"),
	reviewedAt: integer("reviewed_at"),
	reviewedBy: text("reviewed_by"),
	reviewNotes: text("review_notes"),
	createdAt: integer("created_at").notNull(),
	updatedAt: integer("updated_at").notNull(),
});

export const internalSubmissions = sqliteTable("internal_submissions", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	internalFormId: integer("internal_form_id").notNull().references(() => internalForms.id),
	version: integer().default(1).notNull(),
	formData: text("form_data").notNull(),
	isDraft: integer("is_draft", { mode: "boolean" }).default(true).notNull(),
	submittedBy: text("submitted_by"),
	createdAt: integer("created_at").notNull(),
});

export const notifications = sqliteTable("notifications", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").references(() => workflows.id),
	applicantId: integer("applicant_id").references(() => applicants.id),
	type: text().notNull(),
	message: text().notNull(),
	read: integer("read", { mode: "boolean" }).default(false),
	createdAt: integer("created_at"),
	actionable: integer("actionable", { mode: "boolean" }).default(false),
	severity: text().default("medium"),
	groupKey: text("group_key"),
	sourceEventType: text("source_event_type"),
});

export const quotes = sqliteTable("quotes", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").references(() => applicants.id),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	amount: integer().notNull(),
	baseFeePercent: integer("base_fee_percent").notNull(),
	adjustedFeePercent: integer("adjusted_fee_percent"),
	details: text(),
	rationale: text(),
	status: text().default("draft").notNull(),
	generatedBy: text("generated_by").default("platform").notNull(),
	createdAt: integer("created_at").notNull(),
	updatedAt: integer("updated_at").notNull(),
});

export const reApplicantAttempts = sqliteTable("re_applicant_attempts", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	matchedDenyListId: integer("matched_deny_list_id").notNull().references(() => workflowTerminationDenyList.id),
	matchedOn: text("matched_on").notNull(),
	matchedValue: text("matched_value").notNull(),
	deniedAt: integer("denied_at").notNull(),
});

export const riskAssessments = sqliteTable("risk_assessments", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	overallScore: integer("overall_score"),
	overallStatus: text("overall_status"),
	overallRisk: text("overall_risk"),
	procurementData: text("procurement_data"),
	itcData: text("itc_data"),
	sanctionsData: text("sanctions_data"),
	ficaData: text("fica_data"),
	cashFlowConsistency: text("cash_flow_consistency"),
	dishonouredPayments: integer("dishonoured_payments"),
	averageDailyBalance: integer("average_daily_balance"),
	accountMatchVerified: text("account_match_verified"),
	letterheadVerified: text("letterhead_verified"),
	aiAnalysis: text("ai_analysis"),
	reviewedBy: text("reviewed_by"),
	reviewedAt: integer("reviewed_at"),
	notes: text(),
	createdAt: integer("created_at", { mode: "timestamp" }).default(
		new Date("2026-04-11T09:55:23.546Z"),
	),
});

export const riskCheckResults = sqliteTable("risk_check_results", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	checkType: text("check_type").notNull(),
	machineState: text("machine_state").default("pending").notNull(),
	reviewState: text("review_state").default("pending").notNull(),
	provider: text(),
	externalCheckId: text("external_check_id"),
	payload: text(),
	rawPayload: text("raw_payload"),
	errorDetails: text("error_details"),
	startedAt: integer("started_at"),
	completedAt: integer("completed_at"),
	reviewedBy: text("reviewed_by"),
	reviewedAt: integer("reviewed_at"),
	reviewNotes: text("review_notes"),
	createdAt: integer("created_at"),
	updatedAt: integer("updated_at"),
});

export const sanctionClearance = sqliteTable("sanction_clearance", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	sanctionListId: text("sanction_list_id"),
	clearedBy: text("cleared_by").notNull(),
	clearanceReason: text("clearance_reason").notNull(),
	isFalsePositive: integer("is_false_positive").notNull(),
	createdAt: integer("created_at").notNull(),
});

export const signatures = sqliteTable("signatures", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	internalFormId: integer("internal_form_id").notNull().references(() => internalForms.id),
	signatoryName: text("signatory_name").notNull(),
	signatoryRole: text("signatory_role"),
	signatoryIdNumber: text("signatory_id_number"),
	signatureData: text("signature_data").notNull(),
	signatureHash: text("signature_hash").notNull(),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	signedAt: integer("signed_at").notNull(),
});

export const workflowEvents = sqliteTable("workflow_events", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").references(() => workflows.id),
	eventType: text("event_type").notNull(),
	payload: text(),
	timestamp: integer(),
	actorType: text("actor_type").default("platform"),
	actorId: text("actor_id"),
});

export const workflowTerminationDenyList = sqliteTable("workflow_termination_deny_list", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	workflowId: integer("workflow_id").notNull().references(() => workflows.id),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	idNumbers: text("id_numbers").notNull(),
	boardMemberIds: text("board_member_ids").notNull(),
	cellphones: text().notNull(),
	bankAccounts: text("bank_accounts").notNull(),
	boardMemberNames: text("board_member_names").notNull(),
	terminationReason: text("termination_reason").notNull(),
	terminatedAt: integer("terminated_at").notNull(),
	createdAt: integer("created_at").notNull(),
});

export const workflowTerminationScreening = sqliteTable("workflow_termination_screening", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	denyListId: integer("deny_list_id").notNull().references(() => workflowTerminationDenyList.id, { onDelete: "cascade" } ),
	valueType: text("value_type").notNull(),
	value: text().notNull(),
	createdAt: integer("created_at").notNull(),
},
(table) => [
	index("workflow_termination_screening_deny_list_id_idx").on(table.denyListId),
	index("workflow_termination_screening_value_type_value_idx").on(table.valueType, table.value),
]);

export const workflows = sqliteTable("workflows", {
	id: integer().primaryKey({ autoIncrement: true }).notNull(),
	applicantId: integer("applicant_id").notNull().references(() => applicants.id),
	stage: integer().default(1),
	status: text().default("pending"),
	startedAt: integer("started_at"),
	completedAt: integer("completed_at"),
	terminatedAt: integer("terminated_at"),
	terminatedBy: text("terminated_by"),
	terminationReason: text("termination_reason"),
	procurementCleared: integer("procurement_cleared"),
	documentsComplete: integer("documents_complete"),
	aiAnalysisComplete: integer("ai_analysis_complete"),
	mandateRetryCount: integer("mandate_retry_count").default(0),
	mandateLastSentAt: integer("mandate_last_sent_at"),
	riskManagerApproval: text("risk_manager_approval"),
	accountManagerApproval: text("account_manager_approval"),
	contractDraftReviewedAt: integer("contract_draft_reviewed_at"),
	contractDraftReviewedBy: text("contract_draft_reviewed_by"),
	absaPacketSentAt: integer("absa_packet_sent_at"),
	absaPacketSentBy: text("absa_packet_sent_by"),
	absaApprovalConfirmedAt: integer("absa_approval_confirmed_at"),
	absaApprovalConfirmedBy: text("absa_approval_confirmed_by"),
	salesEvaluationStatus: text("sales_evaluation_status"),
	salesIssuesSummary: text("sales_issues_summary"),
	issueFlaggedBy: text("issue_flagged_by"),
	preRiskRequired: integer("pre_risk_required"),
	preRiskOutcome: text("pre_risk_outcome"),
	preRiskEvaluatedAt: integer("pre_risk_evaluated_at"),
	applicantDecisionOutcome: text("applicant_decision_outcome"),
	applicantDeclineReason: text("applicant_decline_reason"),
	stageName: text("stage_name"),
	currentAgent: text("current_agent"),
	reviewType: text("review_type"),
	decisionType: text("decision_type"),
	targetResource: text("target_resource"),
	stateLockVersion: integer("state_lock_version").default(0),
	stateLockedAt: integer("state_locked_at"),
	stateLockedBy: text("state_locked_by"),
	greenLaneRequestedAt: integer("green_lane_requested_at"),
	greenLaneRequestedBy: text("green_lane_requested_by"),
	greenLaneRequestNotes: text("green_lane_request_notes"),
	greenLaneRequestSource: text("green_lane_request_source"),
	greenLaneConsumedAt: integer("green_lane_consumed_at"),
	metadata: text(),
});

