import { Badge, BanknoteIcon, HouseIcon } from "lucide-react";
import { Card, CardContent, CardDescription, CardTitle } from "@/components/ui/card";
import type { RiskReviewData } from "@/lib/risk-review/types";
import { formatVatStatus } from "@/lib/risk-review/vat-status-display";

export function PrintableAuditReport({
	aiSummary,
	data,
}: {
	aiSummary: string | null;
	data: RiskReviewData;
}) {
	if (!data) return null;
	const { globalData, procurementData, itcData, sanctionsData, ficaData } = data;

	return (
		<div className="hidden print:block text-black bg-white font-sans p-8 max-w-4xl mx-auto text-sm">
			<div className="border-b-2 border-black pb-6 mb-6">
				<div className="flex justify-between items-end mb-4">
					<div>
						<h1 className="text-2xl font-bold tracking-tight uppercase">
							Master Compliance & Risk Audit Report
						</h1>
						<p className="text-gray-600 font-medium mt-1">CONFIDENTIAL & PRIVILEGED</p>
					</div>
					<div className="text-right">
						<p className="font-bold">Ref: {globalData.transactionId}</p>
						<p className="text-gray-600">Generated: {globalData.generatedAt}</p>
					</div>
				</div>
			</div>

			{aiSummary && (
				<div className="mb-8 border-2 border-indigo-900 bg-indigo-50 p-4 rounded-sm">
					<h2 className="text-lg font-bold uppercase border-b border-indigo-200 pb-1 mb-3 text-indigo-900">
						AI Adjudication Briefing
					</h2>
					<div className="text-sm whitespace-pre-wrap text-black leading-relaxed">
						{aiSummary}
					</div>
					<p className="text-xs text-indigo-700 italic mt-3 pt-2 border-t border-indigo-200">
						* This summary was generated by AI risk analysis based on the data within this
						report.
					</p>
				</div>
			)}

			<div className="mb-8">
				<h2 className="text-lg font-bold uppercase border-b border-gray-300 pb-1 mb-3">
					1. Executive Summary
				</h2>
				<table className="w-full border-collapse border border-gray-300 mb-4">
					<tbody>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100 w-1/3">Subject Entity Name</td>
							<td className="p-2 w-2/3">
								{globalData.entity.name} (T/A {globalData.entity.tradingAs})
							</td>
						</tr>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100">Registration Number</td>
							<td className="p-2">
								{globalData.entity.registrationNumber} ({globalData.entity.entityType})
							</td>
						</tr>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100">Registered Address</td>
							<td className="p-2">{globalData.entity.registeredAddress}</td>
						</tr>
						<tr>
							<td className="p-2 font-bold bg-gray-100">Overall System Adjudication</td>
							<td className="p-2 font-bold uppercase">
								{globalData.overallStatus} (Risk Score: {globalData.overallRiskScore}/100)
							</td>
						</tr>
					</tbody>
				</table>

				{procurementData?.categories.some(c =>
					c.checks.some(ch => ch.result === "FLAGGED")
				) && (
					<div className="border-l-4 border-black pl-4 py-2 my-4 bg-gray-50">
						<h3 className="font-bold uppercase text-red-700 mb-2">
							CRITICAL EXCEPTIONS IDENTIFIED
						</h3>
						{procurementData.categories
							.flatMap(c =>
								c.checks
									.filter(ch => ch.result === "FLAGGED")
									.map(ch => ({ category: c.id.toUpperCase(), message: ch.name }))
							)
							.map((alert, idx) => (
								<p key={idx} className="mb-1">
									<span className="font-bold">{alert.category}:</span> {alert.message}
								</p>
							))}
					</div>
				)}
			</div>

			<div className="mb-8">
				<h2 className="text-lg font-bold uppercase border-b border-gray-300 pb-1 mb-3">
					2. Procurement & Governance
				</h2>
				{procurementData ? (
					<>
						<div className="grid grid-cols-2 gap-4 mb-4">
							<div>
								<p>
									<span className="font-bold">Entity:</span> {procurementData.vendor.name}
								</p>
								<p>
									<span className="font-bold">Entity Number:</span>{" "}
									{procurementData.vendor.entityNumber}
								</p>
								<p>
									<span className="font-bold">Status:</span>{" "}
									{procurementData.vendor.entityStatus}
								</p>
							</div>
							<div>
								<p>
									<span className="font-bold">Type:</span>{" "}
									{procurementData.vendor.entityType}
								</p>
								<p>
									<span className="font-bold">Tax Number:</span>{" "}
									{procurementData.vendor.taxNumber}
								</p>
							</div>
						</div>

						<h3 className="font-bold mt-4 mb-2">2.1 Category Check Summary</h3>
						<table className="w-full border-collapse border border-gray-300 text-sm">
							<thead className="bg-gray-100">
								<tr>
									<th className="border border-gray-300 p-2 text-left">Category</th>
									<th className="border border-gray-300 p-2 text-center">Total</th>
									<th className="border border-gray-300 p-2 text-center">Executed</th>
									<th className="border border-gray-300 p-2 text-center">Outstanding</th>
									<th className="border border-gray-300 p-2 text-center">Status</th>
								</tr>
							</thead>
							<tbody>
								{procurementData.summary.categories.map((cat, idx) => (
									<tr key={idx}>
										<td className="border border-gray-300 p-2">{cat.category}</td>
										<td className="border border-gray-300 p-2 text-center">
											{cat.total}
										</td>
										<td className="border border-gray-300 p-2 text-center">
											{cat.executed}
										</td>
										<td className="border border-gray-300 p-2 text-center">
											{cat.outstanding}
										</td>
										<td className="border border-gray-300 p-2 text-center font-bold">
											{cat.status}
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</>
				) : (
					<p className="italic text-gray-500">Procurement check pending</p>
				)}
			</div>

			<div className="mb-8">
				<h2 className="text-lg font-bold uppercase border-b border-gray-300 pb-1 mb-3">
					3. Commercial Credit Profile (ITC)
				</h2>
				<table className="w-full border-collapse border border-gray-300">
					<tbody>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100 w-1/3">Credit Score</td>
							<td className="p-2 w-2/3">
								{itcData.creditScore} ({itcData.scoreBand})
							</td>
						</tr>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100">Civil Judgements</td>
							<td className="p-2">{itcData.judgements}</td>
						</tr>
						<tr className="border-b border-gray-300">
							<td className="p-2 font-bold bg-gray-100">Payment Defaults</td>
							<td className="p-2">
								{itcData.defaults} ({itcData.defaultDetails})
							</td>
						</tr>
						<tr>
							<td className="p-2 font-bold bg-gray-100">Trade References</td>
							<td className="p-2">{itcData.tradeReferences}</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div className="mb-8">
				<h2 className="text-lg font-bold uppercase border-b border-gray-300 pb-1 mb-3">
					4. Sanctions, PEP & Adverse Media (WorldCheck)
				</h2>
				<p className="mb-2">
					<span className="font-bold">Global Sanctions Match:</span>{" "}
					{sanctionsData.sanctionsMatch}
				</p>
				<p className="mb-2">
					<span className="font-bold">Politically Exposed Persons (PEP) Hits:</span>{" "}
					{sanctionsData.pepHits}
				</p>

				{sanctionsData.alerts.length > 0 && (
					<div className="mt-4">
						<h3 className="font-bold mb-2">4.1 Adverse Media & Alerts Log</h3>
						<table className="w-full border-collapse border border-gray-300">
							<thead className="bg-gray-100">
								<tr>
									<th className="border border-gray-300 p-2 text-left">Date</th>
									<th className="border border-gray-300 p-2 text-left">Source</th>
									<th className="border border-gray-300 p-2 text-left">Detail</th>
									<th className="border border-gray-300 p-2 text-center">Severity</th>
								</tr>
							</thead>
							<tbody>
								{sanctionsData.alerts.map((alert, idx) => (
									<tr key={idx}>
										<td className="border border-gray-300 p-2 whitespace-nowrap">
											{alert.date}
										</td>
										<td className="border border-gray-300 p-2">{alert.source}</td>
										<td className="border border-gray-300 p-2">{alert.title}</td>
										<td className="border border-gray-300 p-2 text-center font-bold">
											{alert.severity}
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>
				)}
			</div>

			<div className="mb-8">
				<h2 className="text-lg font-bold uppercase border-b border-gray-300 pb-1 mb-3 text-black">
					5. FICA / KYC Validations
				</h2>
				<div className="grid grid-cols-2 gap-6">
					<div>
						<h3 className="font-bold mb-2 border-b border-gray-200 pb-4 text-black1">
							5.1 Natural Person Verification
						</h3>
						{ficaData.identity.map((identity, idx) => (
							<div key={idx} className="mb-2">
								<p className="font-bold text-black">
									{identity.name} ({identity.id})
								</p>
								<p className="text-xs text-black">
									HANIS Status: {identity.status} | Life Status: {identity.deceasedStatus}
								</p>
							</div>
						))}
					</div>
					<div className="flex gap-3">
						<h3 className="font-bold mb-2 border-b border-gray-200 pb-1 text-black">
							<HouseIcon />
							5.2 Proof of Residence
						</h3>
						<p className="text-sm font-bold">{ficaData.residence.address}</p>
						<p className="text-xs mt-1">Source: {ficaData.residence.documentType}</p>
						<p className="text-xs">
							Document Age: {ficaData.residence.ageInDays} Days (
							{ficaData.residence.status})
						</p>
					</div>
				</div>

				<Card className="relative mt-4">
					<CardTitle>
						<BanknoteIcon />
						<span> 5.3 Banking Verification (AVS)</span>
						AVS Match:
					</CardTitle>
					<Badge className="text-sm">{ficaData.banking.avsStatus}</Badge>
					<CardDescription>{ficaData.banking.avsDetails}</CardDescription>
					<CardContent>
						<p className="text-sm">
							<span className="font-bold">Account:</span> {ficaData.banking.bankName}
						</p>
					</CardContent>
				</Card>

				<div className="mt-4">
					<h3 className="font-bold mb-2 border-b border-gray-200 pb-1">
						5.4 VAT Verification
					</h3>
					<p className="text-sm">
						<span className="font-bold">Status:</span>{" "}
						{formatVatStatus(ficaData.vatVerification?.status ?? "not_checked")}
					</p>
					<p className="text-sm">
						<span className="font-bold">VAT Number:</span>{" "}
						{ficaData.vatVerification?.vatNumber || "Not provided"}
					</p>
					{ficaData.vatVerification?.tradingName ? (
						<p className="text-sm">
							<span className="font-bold">Trading Name:</span>{" "}
							{ficaData.vatVerification.tradingName}
						</p>
					) : null}
					{ficaData.vatVerification?.office ? (
						<p className="text-sm">
							<span className="font-bold">Office:</span> {ficaData.vatVerification.office}
						</p>
					) : null}
					{ficaData.vatVerification?.message ? (
						<p className="text-xs mt-1">{ficaData.vatVerification.message}</p>
					) : null}
				</div>
			</div>

			<div className="mt-12 pt-4 border-t-2 border-black text-center text-xs text-gray-500">
				<p>This report was generated by the StratCol Control Tower's System.</p>
				<p>
					Data provided by Procurecheck, the Department of Home Affairs, OpenSanctions,
					XDS WerbServices, BizPortal, SARS, UN Sanctions List, Google Identity Proofing,
					Firecrawl and Google Gemini
				</p>
				<p className="mt-2 font-bold uppercase">End of Report</p>
			</div>
		</div>
	);
}
